// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjtnjaimqtumxhrtlcip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqdG5qYWltcXR1bXhocnRsY2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMTM1ODksImV4cCI6MjA4Njg4OTU4OX0.pI4sekHyXfMmrkwwj7vzquq6dIXdt_8CE30tS_yCEJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});